---
- name: configure ip6tables rules
  copy:
    src: files/firewall-ipv6.sh
    dest: /etc/firewall-ipv6.sh
    owner: root
    group: root
    mode: 0744

- name: Copy ipv6 firewall init script into place
  copy:
    src: files/firewall-ipv6
    dest: /etc/init.d/firewall-ipv6
    owner: root
    group: root
    mode: 0755

- name: Ensure the ipv6 firewall is enabled and will start on boot.
  service:
    name: firewall
    state:  started
    enabled:  yes
