---
- include: firewall-ipv6.yml
  tags: firewall

- include: fail2ban.yml
  tags: fail2ban

- include: nginx.yml
  tags: nginx

- include: exim4.yml
  tags: exim4
  when: "{{enable_mta}}"

- include: remove-exim4.yml
  tags: exim4
  when: not {{enable_mta}}

- include: sandstorm-verify.yml
  tags: sandstorm_verify
  when: sandstorm_verify_installer

- include: sandstorm.yml
  tags: sandstorm

- include: sshd.yml
  tags: ssh

- include: needrestart.yml
  tags: needrestart

- include: backups.yml
  tags: backups
  when: backups

- include: tor.yml
  tags: tor
  when: ssh_onion or sandstorm_onion
    
- include: filebeat.yml
  tags: filebeat
